# Change these first
owner: pavelloz # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Documentation
    url: https://documentation.platformos.com
  - name: Marketing Site
    url: https://www.platformos.com
  - name: Partner Portal
    url: https://partners.platformos.com/
  - name: Sydney
    url: https://prod01.sydney.platformos.com/ping
  - name: Oregon
    url: https://prod01.oregon.platform-os.com/ping
  - name: London
    url: https://prod01.london.platform-os.com/ping
  - name: Staging
    url: https://staging.oregon.platformos.com/ping

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Uptime of platformOS stacks"
  # introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
